#!/bin/bash

#Change the server IP to your private IP.
TC_SERVER_IP="http://192.168.100.204"

docker stop teamcity-agent
docker rm   teamcity-agent

docker run --name teamcity-agent -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/bin/docker -v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/lib/x86_64-linux-gnu/libapparmor.so.1 -e TEAMCITY_SERVER=$TC_SERVER_IP -dt -p 9090:9090 -t adamdelarosa/tc-agent

